# Generated by Django 3.2.12 on 2022-04-08 13:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('djfritz', '0003_hostmodel_wan_access'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostGroupModel',
            fields=[
                ('create_dt', models.DateTimeField(blank=True, editable=False, help_text='ModelTimetrackingMixin.create_dt.help_text', null=True, verbose_name='ModelTimetrackingMixin.create_dt.verbose_name')),
                ('update_dt', models.DateTimeField(blank=True, editable=False, help_text='ModelTimetrackingMixin.update_dt.help_text', null=True, verbose_name='ModelTimetrackingMixin.update_dt.verbose_name')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='BaseModel.id.help_text', primary_key=True, serialize=False, verbose_name='BaseModel.id.verbose_name')),
                ('name', models.CharField(help_text='HostGroupModel.name.help_text', max_length=63, verbose_name='HostGroupModel.name.verbose_name')),
            ],
            options={
                'verbose_name': 'HostGroupModel.verbose_name',
                'verbose_name_plural': 'HostGroupModel.verbose_name_plural',
            },
        ),
        migrations.AddField(
            model_name='hostmodel',
            name='group',
            field=models.ForeignKey(help_text='HostModel.group.help_text', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hosts', to='djfritz.hostgroupmodel', verbose_name='HostModel.group.verbose_name'),
        ),
    ]
