# https://github.com/actions/setup-python

name: Test

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '0 8 * * *'

jobs:
  test:
    name: '${{ matrix.os }} Python ${{ matrix.python-version }} Django ${{ matrix.django }}'
    runs-on: ${{ matrix.os }}
    env:
      PYTHONUNBUFFERED: 1
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest] # TODO: macOS-latest, windows-latest ;)
        python-version: ["3.10", "3.9", "3.8"]
        django: ["3.2", "4.0"]
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: 'fetch main'
      run: |
        git fetch origin main
    - name: 'Set up Python ${{ matrix.python-version }}'
      uses: actions/setup-python@v4
      with:
        python-version: '${{ matrix.python-version }}'

    - name: Setup Github Cache
      uses: actions/cache@v3
      with:
        key: dot-cache-${{ matrix.os }}-${{ matrix.python-version }}-${{ matrix.django }}
        path: ~/.cache/

    - name: 'Bootstrap'
      run: |
        ./devshell.py quit

    - name: 'List installed packages'
      run: |
        ./devshell.py list_venv_packages

    - name: 'List all tox test environments'
      run: |
        ./devshell.py tox --listenvs

    - name: 'Run tests on ${{ matrix.os }} with Python ${{ matrix.python-version }} Django ${{ matrix.django }}'
      run: |
        ./devshell.py tox -e python-django${{ matrix.django }}

    - name: 'Upload coverage report'
      uses: codecov/codecov-action@v2
      with:
        fail_ci_if_error: false
        verbose: true
